export interface SeedListing {
  title: string;
  rawDescription: string;
  pricePerNight: number;
  bedrooms: number;
  location: string;
  latitude: number;
  longitude: number;
}

export const seedListings: SeedListing[] = [
  {
    title: 'Ski-in Chalet on Red Mountain',
    rawDescription: `Wake up to the Elk Range framed in every window of this four-bedroom chalet, a five-minute walk from the Silver Queen Gondola. The great room has a wood-burning fireplace, radiant-heated floors, and a wraparound deck built for watching the sunset hit the peaks. We're a pet-friendly property — bring your dog, just let us know ahead of time so we can leave extra towels by the door. Full chef's kitchen, hot tub, and a heated garage for ski gear.`,
    pricePerNight: 675,
    bedrooms: 4,
    location: 'Aspen, CO',
    latitude: 39.1911,
    longitude: -106.8175,
  },
  {
    title: 'Off-Grid Yurt Above Telluride',
    rawDescription: `A solar-powered yurt at 9,200 feet, reachable by a short hike from the trailhead parking. Wood stove, composting toilet, no cell service.`,
    pricePerNight: 95,
    bedrooms: 0,
    location: 'Telluride, CO',
    latitude: 37.9375,
    longitude: -107.8123,
  },
  {
    title: 'Cabin at the Base of the Tetons',
    rawDescription: `This hand-hewn log cabin sits on five acres with an unobstructed view of the Teton Range from the front porch. Two bedrooms, a loft with a queen bed, and a stone fireplace. Out back you'll find a fenced run, a couple of weatherproof dog beds on the porch, and a hose station for muddy paws after a hike. Ten minutes from town, twenty from the park entrance.`,
    pricePerNight: 340,
    bedrooms: 2,
    location: 'Jackson, WY',
    latitude: 43.4799,
    longitude: -110.7624,
  },
  {
    title: 'The Canopy House',
    rawDescription: `Twenty-two feet up in a stand of old oaks, this one-room treehouse has a queen bed, a wood stove, and a deck that puts you eye-level with the ridgeline rolling out toward the Blue Ridge Parkway. Reached by a suspension bridge from the main property — not recommended for small children or anyone uneasy with heights. Unfortunately we can't accommodate pets here; the access bridge and the neighboring farm's chickens don't mix well with dogs.`,
    pricePerNight: 165,
    bedrooms: 0,
    location: 'Asheville, NC',
    latitude: 35.5951,
    longitude: -82.5515,
  },
  {
    title: '2BR Condo, Park City Golf Course',
    rawDescription: `Second-floor unit overlooking the 14th fairway. Two bedrooms, two baths, sleeps 6. In-unit laundry, assigned parking, shared clubhouse pool and gym access. Walking distance to Main Street shuttle stop.`,
    pricePerNight: 285,
    bedrooms: 2,
    location: 'Park City, UT',
    latitude: 40.6461,
    longitude: -111.498,
  },
  {
    title: "Our Family's Lake Cabin",
    rawDescription: `We've owned this cabin since my kids were small, and it still feels like the best place on earth to disconnect. From the back deck you can see the whole lake and the pine ridge behind it, especially gorgeous around sunset. Three bedrooms, a loft with bunk beds, and a dock permit you're welcome to use. We keep a couple of dog bowls and an old towel bin by the mudroom door for anyone traveling with a four-legged friend.`,
    pricePerNight: 310,
    bedrooms: 3,
    location: 'Big Bear Lake, CA',
    latitude: 34.2439,
    longitude: -116.9114,
  },
  {
    title: 'Restored 1850s Farmhouse',
    rawDescription: `A carefully restored farmhouse on eleven acres, twenty minutes from Stowe Mountain Resort. Original wide-plank floors, a wood cookstove in the kitchen, and four bedrooms furnished with antiques sourced from estate sales around the county. The sugar maples climb the hillside right behind the barn, and in October the whole slope turns the kind of color you see on postcards. Please note: due to a severe allergy in the caretaker's family, we are unable to host pets of any kind.`,
    pricePerNight: 295,
    bedrooms: 4,
    location: 'Stowe, VT',
    latitude: 44.4654,
    longitude: -72.6874,
  },
  {
    title: 'Ski-In/Ski-Out Luxury Condo with Peak 8 Views',
    rawDescription: `Step out your door and onto the slopes! This stunning three-bedroom condo delivers jaw-dropping views of Peak 8 and the Tenmile Range from a private balcony with a hot tub. Gourmet kitchen, stone fireplace, heated boot room. Bringing the pup? Great — we're proud to be one of the few true ski-in/ski-out buildings in Breckenridge that welcomes dogs, no extra fee for stays under a week.`,
    pricePerNight: 590,
    bedrooms: 3,
    location: 'Breckenridge, CO',
    latitude: 39.4817,
    longitude: -106.0384,
  },
  {
    title: 'Cottage Two Blocks from Haystack Rock',
    rawDescription: `Cute little two-bedroom, one block off the beach path. Sit on the porch and watch the waves break around Haystack Rock — front-row seat, honestly. There's an outdoor shower and a paw-wash station by the side gate that gets a lot of use, plus a couple of leash hooks by the door for quick trips to the sand.`,
    pricePerNight: 220,
    bedrooms: 2,
    location: 'Cannon Beach, OR',
    latitude: 45.8918,
    longitude: -123.9615,
  },
  {
    title: 'The Bramblewood Cottage',
    rawDescription: `A quintessential New England cottage in the heart of Kennebunkport's historic district, within walking distance of Dock Square. Three bedrooms furnished in a traditional coastal style, a screened porch, and a formal dining room suited to entertaining. As a matter of house policy, pets are not permitted on the premises under any circumstances.`,
    pricePerNight: 265,
    bedrooms: 3,
    location: 'Kennebunkport, ME',
    latitude: 43.3612,
    longitude: -70.4762,
  },
  {
    title: 'Oceanfront House — Nags Head',
    rawDescription: `- 5 bedrooms, 3 baths, sleeps 12
- Direct beach access, unobstructed Atlantic views from every level
- Private pool, elevator, two covered decks
- Fully equipped kitchen, 3 dedicated parking spots
- Weekly rentals only during peak season`,
    pricePerNight: 480,
    bedrooms: 5,
    location: 'Nags Head, NC',
    latitude: 35.9573,
    longitude: -75.6241,
  },
  {
    title: 'Shrimp Boat Row Bungalow',
    rawDescription: `Grab a coffee and sit out on the porch — most mornings you can watch the shrimp boats head out past the sound before the tourists are even awake. This one-bedroom bungalow is small but well loved, with a claw-foot tub and a porch swing that everyone fights over. Dogs are more than welcome; we even keep a jar of treats on the counter for well-behaved guests of the four-legged variety.`,
    pricePerNight: 175,
    bedrooms: 1,
    location: 'Tybee Island, GA',
    latitude: 32.0135,
    longitude: -80.8456,
  },
  {
    title: 'Cypress Bluff Cottage',
    rawDescription: `Perched at the edge of a headland where the Pacific has spent ten thousand years carving the cliffs into arches and sea stacks, this cottage offers a view that changes by the hour — fog rolling in by mid-morning, then burning off to reveal whales if you're lucky and patient. Two bedrooms, a wood stove, and a claw-foot tub positioned, deliberately, to face the window.`,
    pricePerNight: 385,
    bedrooms: 2,
    location: 'Mendocino, CA',
    latitude: 39.3076,
    longitude: -123.7994,
  },
  {
    title: 'Beach House Near the Boardwalk',
    rawDescription: `Three-bedroom rental a short drive from the boardwalk and the go-kart track. Crate available on request, fenced side yard, dog waste bags provided at check-in. Full kitchen, washer/dryer, sleeps 8.`,
    pricePerNight: 190,
    bedrooms: 3,
    location: 'Ocean Shores, WA',
    latitude: 46.9737,
    longitude: -124.1571,
  },
  {
    title: 'Carriage House on Tradd Street',
    rawDescription: `Located in a meticulously preserved carriage house dating to 1843, in the heart of Charleston's historic district south of Broad. The unit retains its original heart-pine floors and twelve-foot ceilings, furnished with period-appropriate antiques. Given the age and delicacy of the furnishings, we regretfully cannot accommodate pets.`,
    pricePerNight: 340,
    bedrooms: 1,
    location: 'Charleston, SC',
    latitude: 32.7765,
    longitude: -79.9311,
  },
  {
    title: 'West End Cottage, Steps to the Harbor',
    rawDescription: `A quiet one-bedroom cottage in Provincetown's West End, a five-minute walk to the harbor and the galleries on Commercial Street. The back deck looks out over the breakwater, especially striking at low tide when the flats stretch out toward Long Point. Bike rentals available next door.`,
    pricePerNight: 245,
    bedrooms: 1,
    location: 'Provincetown, MA',
    latitude: 42.0584,
    longitude: -70.1786,
  },
  {
    // Describes a nearby dog park, not the unit's own pet policy — treat as ambiguous/null
    // pet-policy ground truth, not "implicit pet-friendly", in eval test data (Phase 8).
    title: 'Rainey Street Loft',
    rawDescription: `Industrial loft in a converted warehouse two blocks from Rainey Street's bars and food trucks. Exposed brick, polished concrete floors, a rooftop deck shared with three other units. There's a dog park directly across the street if you're traveling with one — half the building seems to use it every morning.`,
    pricePerNight: 210,
    bedrooms: 1,
    location: 'Austin, TX',
    latitude: 30.2672,
    longitude: -97.7431,
  },
  {
    title: 'Solar Craftsman in Mount Tabor',
    rawDescription: `A 1912 craftsman we've restored with an eye toward sustainability — solar panels, a rainwater catchment system for the garden, and a compost setup you're welcome to use. Three bedrooms, original fir floors, a covered porch. Well-behaved dogs are always welcome; we love hosting fellow dog people and keep the backyard securely fenced for exactly that reason.`,
    pricePerNight: 195,
    bedrooms: 3,
    location: 'Portland, OR',
    latitude: 45.5152,
    longitude: -122.6784,
  },
  {
    title: 'Loop High-Rise, Lake and Skyline Views',
    rawDescription: `Corporate-standard one-bedroom on the 34th floor of a full-service building in the Loop. Floor-to-ceiling windows frame Lake Michigan to the east and the skyline to the west — a dramatic backdrop for both morning coffee and evening calls. Building amenities include a 24-hour fitness center, business lounge, and doorman. Per building policy, no pets are permitted.`,
    pricePerNight: 265,
    bedrooms: 1,
    location: 'Chicago, IL',
    latitude: 41.8781,
    longitude: -87.6298,
  },
  {
    title: 'East Nashville Bungalow, Walk to Five Points',
    rawDescription: `A colorful little bungalow in East Nashville, a few minutes' walk from the bars and coffee shops around Five Points. One bedroom plus a daybed in the sunroom, record player and a decent vinyl collection included. Front porch is the real selling point — great for evenings.`,
    pricePerNight: 155,
    bedrooms: 1,
    location: 'Nashville, TN',
    latitude: 36.1627,
    longitude: -86.7816,
  },
  {
    title: 'LoHi Apartment with Balcony',
    rawDescription: `One-bedroom apartment in the LoHi neighborhood, walking distance to Highlands Square. On clear days you can pick out the Front Range from the balcony, especially around sunset. In-unit washer/dryer, one reserved parking spot, rooftop deck shared with the building.`,
    pricePerNight: 175,
    bedrooms: 1,
    location: 'Denver, CO',
    latitude: 39.7392,
    longitude: -104.9903,
  },
  {
    // Describes a nearby dog run/pet-supply shop, not the unit's own pet policy — treat as
    // ambiguous/null pet-policy ground truth, not "implicit pet-friendly", in eval test data (Phase 8).
    title: 'Capitol Hill Apartment, Skyline View',
    rawDescription: `Top-floor unit in a small walk-up on Capitol Hill. The living room window looks straight down toward downtown and Elliott Bay, especially nice around sunset when the ferries are crossing. One bedroom, gas stove, small balcony. There's a fenced dog run two buildings over and a pet-supply shop on the corner — you'll see why half the block seems to have a dog.`,
    pricePerNight: 205,
    bedrooms: 1,
    location: 'Seattle, WA',
    latitude: 47.6062,
    longitude: -122.3321,
  },
  {
    title: 'Shotgun Apartment in the Marigny',
    rawDescription: `Classic shotgun-style apartment in the Faubourg Marigny, a short walk from Frenchmen Street. High ceilings, original hardwood floors, a courtyard shared with the unit next door. Note for guests: the building's HOA prohibits pets of any kind, no exceptions, so please don't ask us to make one.`,
    pricePerNight: 165,
    bedrooms: 2,
    location: 'New Orleans, LA',
    latitude: 29.9511,
    longitude: -90.0715,
  },
  {
    title: 'Downtown Minneapolis Studio',
    rawDescription: `Clean, simple studio near the skyway system. Good for a short business trip.`,
    pricePerNight: 95,
    bedrooms: 0,
    location: 'Minneapolis, MN',
    latitude: 44.9778,
    longitude: -93.265,
  },
  {
    title: 'Garden-Level Unit, Squirrel Hill',
    rawDescription: `Private entrance, small kitchenette, queen bed. Quiet street.`,
    pricePerNight: 75,
    bedrooms: 0,
    location: 'Pittsburgh, PA',
    latitude: 40.4406,
    longitude: -79.9959,
  },
  {
    title: 'Whitefish Lake Lodge — Six Bedrooms',
    rawDescription: `A big timber-frame lodge built for large groups and reunions, six bedrooms across three levels plus a bunk room that sleeps four more. Whitefish Lake and the Big Mountain ski runs are both visible from the great room's wall of windows. We host a lot of multi-generational family trips here, dogs included — there's a mudroom built specifically for muddy boots and wet dogs coming in from the lake.`,
    pricePerNight: 780,
    bedrooms: 6,
    location: 'Whitefish, MT',
    latitude: 48.4108,
    longitude: -114.3376,
  },
  {
    title: '1BR Condo Near Sun Valley Village',
    rawDescription: `Simple, clean one-bedroom condo a short walk from Sun Valley Village. Ski storage in the unit, shared hot tub and sauna in the building, on-site parking included.`,
    pricePerNight: 225,
    bedrooms: 1,
    location: 'Ketchum, ID',
    latitude: 43.6805,
    longitude: -114.3638,
  },
  {
    title: 'Adobe Casita Near the Gorge',
    rawDescription: `A handmade adobe casita built by the owner's grandfather, on a quiet road outside town. From the kiva-style fireplace room, you can just make out the rim of the Rio Grande Gorge past the sagebrush when the light's right in the evening. There's a fenced acre out back if you're bringing a dog, plus a water trough by the gate that doubles nicely as a dog bowl.`,
    pricePerNight: 145,
    bedrooms: 2,
    location: 'Taos, NM',
    latitude: 36.4072,
    longitude: -105.5731,
  },
  {
    title: 'Floating Home on Richardson Bay',
    rawDescription: `A genuine floating home moored in Sausalito's houseboat community, not a boat you drive — just a very well-appointed home that happens to sit on the water. The main room's windows frame the bay and the Sausalito hillside directly across the water, with the Golden Gate Bridge visible from the upper deck on clear days. One bedroom, a small galley kitchen, and a deck that becomes the whole point of staying here.`,
    pricePerNight: 315,
    bedrooms: 1,
    location: 'Sausalito, CA',
    latitude: 37.8591,
    longitude: -122.4852,
  },
  {
    title: 'The Silo — Converted Grain Silo Stay',
    rawDescription: `We turned an old grain silo into a genuinely comfortable one-room stay — curved walls, a spiral stair up to the sleeping loft, big skylight over the bed. It's on a working property with a few barn cats and a very friendly Australian shepherd, so if your dog does well around livestock, bring them along; if not, this might not be the spot.`,
    pricePerNight: 165,
    bedrooms: 0,
    location: 'Fredericksburg, TX',
    latitude: 30.2752,
    longitude: -98.8719,
  },
  {
    title: 'Vintage Airstream in the High Desert',
    rawDescription: `A restored 1970s Airstream parked on a few acres outside Marfa, far enough from town that the stars actually look the way people say they do out here. Nothing but scrub and open sky in every direction, and the sunsets are the kind that make you forget to eat dinner on time.`,
    pricePerNight: 120,
    bedrooms: 0,
    location: 'Marfa, TX',
    latitude: 30.3097,
    longitude: -104.0177,
  },
  {
    title: 'Fire Lookout Tower Stay, Cascades',
    rawDescription: `A decommissioned fire lookout tower, forty feet up, with 360-degree views of the Enchantments and the Wenatchee River valley below. Reached via a steep half-mile trail — you'll need to carry your own gear up. One room, propane stove, no running water. Because of the access trail and the tower's small footprint, we can't accommodate pets on this one.`,
    pricePerNight: 135,
    bedrooms: 0,
    location: 'Leavenworth, WA',
    latitude: 47.5962,
    longitude: -120.6615,
  },
  {
    title: 'Red Rock Retreat',
    rawDescription: `A single-story house tucked against the base of Thunder Mountain, with red rock formations visible from nearly every window, including the primary bedroom. Four bedrooms, a hot tub on the back patio angled toward Cathedral Rock, and a fully stocked kitchen. Dogs are welcome — we ask only that they stay off the furniture, and we're happy to recommend nearby trails that allow leashed pets.`,
    pricePerNight: 425,
    bedrooms: 4,
    location: 'Sedona, AZ',
    latitude: 34.8697,
    longitude: -111.761,
  },
  {
    title: 'Garden Level Apartment, Forsyth Park',
    rawDescription: `A quiet one-bedroom apartment half a block from Forsyth Park, in a building with the kind of wrought-iron balconies Savannah is known for. Original heart-pine floors, a claw-foot tub, and a small private courtyard shared with one other unit. Walking distance to most of the historic district's restaurants.`,
    pricePerNight: 165,
    bedrooms: 1,
    location: 'Savannah, GA',
    latitude: 32.0809,
    longitude: -81.0912,
  },
  {
    title: 'Beachfront House on Kailua Bay',
    rawDescription: `A two-bedroom house directly on Kailua Beach, consistently rated one of the best beaches in the country. Sliding doors off the living room open right onto the sand, with the Mokulua Islands visible offshore. Please note that due to an agreement with our property association, pets are not permitted at this address.`,
    pricePerNight: 495,
    bedrooms: 2,
    location: 'Kailua, HI',
    latitude: 21.4022,
    longitude: -157.7394,
  },
];
